### ISSUE TITLE
TCP connection issue

### ISSUE THREAD

**Issue by akycdi** [leon-ai/leon#397]
I am getting a error while starting the  gitpod browser version
![image](https://user-images.githubusercontent.com/84339290/181222913-f73c285f-f532-4fbf-b16c-e3a1dbf7aff2.png)

**Comment by louistiti** [comment]
Hi @akycdi :wave:,

Thanks for notifying. Indeed, since the 1.0.0-beta.7 version, Leon includes a TCP server and client. It will need further investigation to make it work with Gitpod.

**Comment by louistiti** [comment]
The issue has been fixed. It was due to a virtual env conflict while installing the spaCy models. Also, I modified the Gitpod file so Leon automatically install and run via the Leon CLI. Enjoy!

Let me know if you see any other issue.

**Comment by ocervell** [comment]
@louistiti still getting the same error on the latest master

**Comment by milosb793** [comment]
I'm getting the same error!

**Comment by danielchicote** [comment]
`.: TCP CLIENT :.
🚨 Failed to connect to the TCP server
ℹ️  Trying to connect to the TCP server...`

**Comment by louistiti** [comment]
@ocervell @milosb793 @danielchicote hello, please [join us on Discord](https://discord.com/invite/MNQqqKg) so we can check together. This issue will be updated if anything needs to be followed up.

**Comment by louistiti** [comment]
Just in case similar issue happens on this side. Try the following:

1. Get the path of where your Leon is installed. You will see a `Path` value
```sh
leon info
```
2. Go to the path
3. Delete the `.leon/bridges/python/.venv` folder
4. From your `.leon` folder, run:
```sh
npm run postinstall
```

**Comment by luogao** [comment]
> Just in case similar issue happens on this side. Try the following:
> 
> 1. Get the path of where your Leon is installed. You will see a `Path` value:
> 
> ```shell
> leon info
> ```
> 
> 2. Go to the path
> 3. Delete the `.leon/bridges/python/.venv` folder
> 4. From your `.leon` folder, run:
> 
> ```shell
> npm run postinstall
> ```

I tried this way, but still not working, and I get this error 
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/22949684/195661895-a84b5833-b90d-45df-9227-86223acceb2f.png">

**Comment by louistiti** [comment]
> > Just in case similar issue happens on this side. Try the following:
> > 
> > 1. Get the path of where your Leon is installed. You will see a `Path` value:
> > 
> > ```shell
> > leon info
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Go to the path
> > 3. Delete the `.leon/bridges/python/.venv` folder
> > 4. From your `.leon` folder, run:
> > 
> > ```shell
> > npm run postinstall
> > ```
> 
> I tried this way, but still not working, and I get this error <img alt="image" width="1384" src="https://user-images.githubusercontent.com/22949684/195661895-a84b5833-b90d-45df-9227-86223acceb2f.png">

May I know if you are using Mac with an M1 chip?

**Comment by luogao** [comment]
> > > Just in case similar issue happens on this side. Try the following:
> > > 
> > > 1. Get the path of where your Leon is installed. You will see a `Path` value:
> > > 
> > > ```shell
> > > leon info
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. Go to the path
> > > 3. Delete the `.leon/bridges/python/.venv` folder
> > > 4. From your `.leon` folder, run:
> > > 
> > > ```shell
> > > npm run postinstall
> > > ```
> > 
> > 
> > I tried this way, but still not working, and I get this error <img alt="image" width="1384" src="https://user-images.githubusercontent.com/22949684/195661895-a84b5833-b90d-45df-9227-86223acceb2f.png">
> 
> May I know if you are using Mac with an M1 chip?

Yes, I'm using Mac with an M1 chip... 🥲

**Comment by louistiti** [comment]
@luogao I'm currently working on the next beta release. This will include already-compiled binaries so we don't need to have all these Python requirements installed, even though the CLI is greatly simplifying it, there are still edge cases.

I tried to compile binaries with macOS on an ARM64 (M1) architecture, and it worked well.

In the meantime, as the current beta version still requires to install Python dependencies, and that `tokenizers` itself requires the Rust compiler to compile from source, you can try the following:

```bash
# Delete the Python deps to avoid caching
rm -rf bridges/python/.venv

# Go to the virtual env source directory
cd bridges/python

# Install/upgrade these deps
pipenv run pip install --upgrade setuptools wheel

# Go back to the Leon root directory
cd -

# Rerun the postinstall script
npm run postinstall

# See if it worked
```

If you have another issue and it mentions that you need the Rust compiler, you can do the following:

```bash
# Get the Rust installer
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Reload configuration to expose the Rust installer to your env
source "$HOME/.cargo/env"

# Check version found
rustc --version

# Delete the Python deps to avoid caching
rm -rf bridges/python/.venv

# Rerun the postinstall script
npm run postinstall
```

**Comment by luogao** [comment]
@louistiti thanks, but I tried your suggestion. But still not working, and still the same error.

**Comment by louistiti** [comment]
> @louistiti thanks, but I tried your suggestion. But still not working, and still the same error.

 Can you try to just `pip install --upgrade setuptools` and retry to see how it goes?

**Comment by molekm** [comment]
Same issue here on Windows

**Comment by louistiti** [comment]
Hi @molekm @luogao @danielchicote @ocervell @akycdi,

This month we have been working on compiling all Python stuff related upfront. Meaning, Leon does not need Python at runtime anymore.

Please try the three following commands and let's see how it goes and paste the report URL:

```bash
# Install the beta version of the Leon CLI
npm install --global @leon-ai/cli@beta

# Create a Leon instance based on the develop GitHub branch
leon create birth --develop

# Create a report
leon check
```
