### ISSUE TITLE
Speech2Text error

### ISSUE THREAD

**Issue by bjadel** [leon-ai/leon#59]
Hi,

I get an error when using STT. I use the offline version of STT and TTS.

### Specs

- Leon version: 1.0.0-beta2
- OS (or browser) version: openSUSE Tumbleweed
- Node.js version: docker version
- Complete "npm run check" output:

`
➜  leon git:(develop) ✗ docker exec -it 97c3b4910a12 sh                     
/app # npm run check

> leon@1.0.0-beta.1 check /app
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.15.2

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /app/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.6

➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✔ {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "output": {"type": "end", "code": "success", "speech": 57, "options": {}}}                                                                      

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
✔ Found Flite at bin/flite/flite

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
✔ Found DeepSpeech language model at bin/deepspeech/lm.binary

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
✔ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
✔ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
`

- (optional) Leon package version:

### Expected Behavior
No error :-)

### Actual Behavior
I get the following error in the docker log:

`
✔ New instance
➡ Initializing STT...
➡ Loading model from file bin/deepspeech/output_graph.pb...
(node:23) UnhandledPromiseRejectionWarning: TypeError: DeepSpeech.Model is not a constructor
    at Object.parser.init.args [as init] (/app/server/dist/stt/deepspeech/parser.js:107:13)
    at Stt.init (/app/server/dist/stt/stt.js:55:27)
    at Socket.socket.on (/app/server/dist/core/server.js:193:17)
    at Socket.emit (events.js:189:13)
    at /app/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
`

Cheers
Björn

**Comment by louistiti** [comment]
Hello @bjadel,

Thanks for reporting. Are you using the `deepspeech` or `deepspeech-gpu` package?

**Comment by bjadel** [comment]
Hello @louistiti,

this is a good question. I connected to the docker container and enabled in the .env file TTS and STT. Then I executed the following two commands inside the container:

`
npm run setup:offline-stt
`

`
npm run setup:offline-tts
`

Where can I see which package he is using?

**Comment by louistiti** [comment]
Alright then I suppose you are using the default one which is `deepspeech`.
Unfortunately I'm not able to reproduce the error right now, I'll try to dig deeper this weekend.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐞 Take a deeper look at the DeepSpeech issue](https://trello.com/c/t9CB7hhY/246-%F0%9F%90%9E-take-a-deeper-look-at-the-deepspeech-issue)

**Comment by louistiti** [comment]
Hello @bjadel,

I took some time to go deeper into that issue. However I was not able to reproduce the error. Maybe you could try on Ubuntu via a VM for example?

Please keep me in touch if you do so.

**Comment by bjadel** [comment]
Hi @louistiti
 
I have aborted further troubleshooting and tried to get it to run without docker. The problem was that I didn't have Python 3.6 installed. I could solve that yesterday with pipenv. Now STT and TTS are running.

Cheers
Björn

**Comment by louistiti** [comment]
Great, thanks for saying.

I'll close that issue as the problem has been solved.

**Comment by jottenwa** [comment]
This issue is still occurring for me when I try to run it in Docker, does anyone have a solution?
